In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])


In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
a+1

array([2, 3, 4, 5, 6])

In [5]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [6]:
a*2

array([ 2,  4,  6,  8, 10])

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
x=np.array([1,2,3,1])
x.mean()
np.median(x)

1.5

In [5]:
x=np.array([[1,2],[0,4]])
x.min()

0

In [2]:
x=np.array([[1],[2],[3],[4]])
y=np.array([1,2,3,4])
x+y

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [7]:
x=x[:,np.newaxis]
x.ravel()

array([1, 2, 3, 4])