# Co-Occurance Matrix

**Co Occurance Matrix is used for finding the semantic relation between the words in the context of words present near by.**

<img src="files/img1.png">
<img src="files/img2.png">

In [4]:
import numpy as np
tokens=['He','is','not','lazy','intelligent','smart']
window=2
m = np.zeros([len(tokens),len(tokens)]) # n is the count of all words
def cal_occ(sentence,m):
  n=sentence.split()
  for i,word in enumerate(sentence.split()):
    #print(word)
    #print('i--',i)
    if word in tokens:
      #print('jsf--')
      for j in range(max(i-window,0),min(i+window+1,len(n))):
        #print('j---',j)
        #print(n[j])
        if (n[j] in tokens) and (n[j] != word):
          #print('jsf')
          m[tokens.index(word),tokens.index(n[j])]+=1
    else:
      continue
          
          

corpus='He is not lazy He is intelligent He is smart'

cal_occ(corpus,m)
print(m)

[[0. 4. 2. 1. 2. 1.]
 [4. 0. 1. 2. 2. 1.]
 [2. 1. 0. 1. 0. 0.]
 [1. 2. 1. 0. 0. 0.]
 [2. 2. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]]


**Co Occurance Matrix is also used as input in Truncated SVD to reduce the number of components**

**Limitation**<br>
It takes a huge amount of memory to store the matrix but the number of components can be reduced by factorization 